services:
  - type: web
    name: SistPRO
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m flask db upgrade && gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase: SistPRO  # ‚Üê Este es el nombre de tu base de datos en Render
      - key: SECRET_KEY
        sync: false